language: php
dist: trusty

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - hhvm
  - nightly

env:
  matrix:
    - SYMFONY_VERSION="3.3.*"
    - SYMFONY_VERSION="3.4.*"

matrix:
  include:
    - php: 5.6
      env: SYMFONY_VERSION=2.8.*
    - php: 7.2
      env: SYMFONY_VERSION=3.4.*



before_script:
    - curl -s http://getcomposer.org/installer | php
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require symfony/symfony:${SYMFONY_VERSION} --no-update; fi
    - php composer.phar install

script: vendor/bin/phpunit --configuration phpunit.xml --coverage-text
