language: php
dist: trusty

php:
  - 7.1
  - 7.2

env:
  matrix:
    - SYMFONY_VERSION="3.4.*"
    - SYMFONY_VERSION="^4.1"

matrix:
  include:
    - php: 7.1
      env: SYMFONY_VERSION=3.4.*
    - php: 7.2
      env: SYMFONY_VERSION="^4.1"

before_script:
    - curl -s http://getcomposer.org/installer | php
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require symfony/symfony:${SYMFONY_VERSION} --no-update; fi
    - php composer.phar install

script: vendor/bin/phpunit --configuration phpunit.xml --coverage-text
